name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build latest
        uses: docker/build-push-action@v6
        with:
          file: ./docker/default.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: sissbruecker/linkding:test
          target: linkding
      - name: Build latest-alpine
        uses: docker/build-push-action@v6
        with:
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: sissbruecker/linkding:test-alpine
          target: linkding
      - name: Build latest-plus
        uses: docker/build-push-action@v6
        with:
          file: ./docker/default.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: sissbruecker/linkding:test
          target: linkding-plus
      - name: Build latest-plus-alpine
        uses: docker/build-push-action@v6
        with:
          file: ./docker/alpine.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: sissbruecker/linkding:test-plus-alpine
          target: linkding-plus
